name: BarsOfAction
description: Create and send ActionBars with ease
main: io.github.vyketype.barsofaction.BarsOfAction
version: 1.3.3
api-version: 1.19
author: vyketype
website: https://github.com/vyketype/BarsOfAction