name: BarsOfAction
description: Create and send actionbars with ease
main: io.github.vyketype.barsofaction.BarsOfAction
version: 1.2
api-version: 1.19
author: vyketype
# website: vyketype.github.io/barsofaction