name: BarsOfAction
description: Create and send ActionBars with ease
main: io.github.vyketype.barsofaction.BarsOfAction
version: 1.3.2-SNAPSHOT
api-version: 1.19
author: vyketype
# website: vyketype.github.io/barsofaction